### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ztblat** [351768593/MinecraftTinkersExporter#2]
Can you add data export for Arcane Focus, Laser Medium?

**Comment by FirokOtaku** [comment]
Information of materials is read and exported from Tinkers' Construct's internal registry at **Minecraft post init phase**. At this time, all mod contents should already be registered and nearly fixed. If any materials from TiC sub-mods is not exported, that should not be our problem.

**Comment by ztblat** [comment]
> Information of materials is read and exported from Tinkers' Construct's internal registry at **Minecraft post init phase**. At this time, all mod contents should already be registered and nearly fixed. If any materials from TiC sub-mods is not exported, that should not be our problem.

Arcane Focus, Laser Medium are not in head、handle、extra interior

**Comment by FirokOtaku** [comment]
Sorry but I have no plan to support exporting more categories of component information from other mods.

**Comment by FirokOtaku** [comment]
Closed.
